version: "3"
services:
  frontend:
    build: frontend
    depends_on:
      - api
    tty: true
    ports:
      - "3000:3000"
  api:
    build: backend
    depends_on:
      - database
    tty: true
    ports:
      - "3001:3001"
    environment:
      - BACKEND_URL=http://api.coinlayer.com/api
      - BACKEND_URL_ACCESS_TOKEN=1c95ea0964647cf493ac0884b0a9ca57
      - DATABASE_URL=mongodb://mongo:27017/cryptocurrency
  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
